FROM logstash:5
RUN logstash-plugin install logstash-input-beats
RUN logstash-plugin install logstash-filter-multiline

# Add your logstash plugins setup here
# Example: RUN logstash-plugin install logstash-filter-json
